name: Deploy Map

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache URL expansions
        uses: actions/cache@v3
        with:
          path: scripts/url_cache.json
          key: url-cache-${{ hashFiles('scripts/generate_map.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium requests notion-client

      - name: Run map generation
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python scripts/generate_map.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
